version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - pgadmin.env 
    ports:
      - 5050:80

volumes:
  postgres-data:
